### ISSUE TITLE
[1.21] Crash on launch on Neoforge 21.0.83

### ISSUE THREAD

**Issue by ffuentesm** [gigaherz/ToolBelt#147]
Log: https://pastebin.com/CNT1Lq3N
Neoforge: 21.0.83
ToolBelt-1.21-2.2.1.jar      

New neoforge update changes causes crash on launch. I think is the new client event hooks

**Comment by Periam** [comment]
I came to report the same problem.
I have installed the below mods

NeoForge 21.0.79

AoA3-1.21-3.7.9.jar
Placebo-1.21-9.3.3.jar
ToolBelt-1.21-2.2.1.jar

Logs
[crash-2024-07-10_09.24.09-client.txt](https://github.com/user-attachments/files/16161909/crash-2024-07-10_09.24.09-client.txt)

[latest.log](https://github.com/user-attachments/files/16161915/latest.log)

[debug.log](https://github.com/user-attachments/files/16161918/debug.log)

**Comment by ffuentesm** [comment]
@Periam  Do you have xaero's world map installed? 
If you remove that it seems to work

**Comment by Periam** [comment]
@ffuentesm  hey, I do not have any other mod installed beside the listed ones.
I do not use that mini map mod..

**Comment by gigaherz** [comment]
I haven't updated most of my mods yet for the latest neoforge. You'll have to be patient.

**Comment by gigaherz** [comment]
I have been looking at the mod and there's no errors in the latest version. However, now that I see the error log, I see that I have seen this error before.

@ffuentesm @Periam  this error happens when **some other error has happened first**, you have to look higher up in the debug.log file because the crash log only shows the error that crashed and not the error that caused the crash to happen.

**Comment by ffuentesm** [comment]
In my case I found it, and it was xaero's world map causing the core problem.
