### ISSUE TITLE
Client crash java.lang.NullPointerException: Rendering screen

### ISSUE THREAD

**Issue by ProsperCraft** [gigaherz/ToolBelt#29]
https://gist.github.com/ProsperCraft/08a9a07954dd045c319022f6c3dfbc1a

**Comment by gigaherz** [comment]
Thanks for the report, I have no idea how my mod could cause that crash, but I'll investigate.

**Comment by ProsperCraft** [comment]
I verified it by disabling it, loading in fine, then re-enabling it again and crashing again.

**Comment by gigaherz** [comment]
Hey, does the issue still happen? I believe those errors may have been caused by errors during registration that didn't show up on screen, but the newer versions of forge fixed that, such that the errors actually appear and stop the loading process. Could you try again with the latest version of forge 1.14.3 and the latest toolbelt?

**Comment by Thyriel** [comment]
Still crashing when pressing "v" button or so in the game
https://pastebin.com/muG1mg8t

**Comment by gigaherz** [comment]
@Thyriel your crash is completely different from the OPs. That said, forge 27.0.21 added a feature that was needed for the recipe book to work, so I'm hoping in the next release your crash will also be fixed.

**Comment by ProsperCraft** [comment]
This no longer happens.
